[package]
name = "server"
version = "0.1.0"
edition = "2024"
license = "MIT"
default-run = "server"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "server"

[[bin]]
path = "src/database/main.rs"
name = "db"

[[bin]]
path = "src/workers/main.rs"
name = "worker"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
axum = "0.8.9"
axum-extra = { version = "0.12.6", features = ["routing"] }
hyper = "1.11.0"
tower = { version = "0.5.3", features = [] }
tower-http = { version = "0.7.0", features = [
  "trace",
  "timeout",
  "request-id",
  "cors",
  "normalize-path",
] }

sea-orm = { version = "2.0.0", features = [
  "runtime-tokio-rustls",
  "sqlx-postgres",
  "macros",
  "with-chrono",
  "with-json",
  "with-uuid",
  "seaography",
] }
sea-orm-migration = { version = "2.0.0", features = ["runtime-tokio-rustls"] }

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }

reqwest = { version = "0.13.4", default-features = false, features = [
  "json",
  "form",
] }
chrono = { version = "0.4.45", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
uuid = { version = "1.24.0", features = ["v7", "serde"] }
dotenvy = "0.15.7"

anyhow = "1.0.104"
thiserror = "2.0.19"
utoipa = "5.5.0"
utoipa-swagger-ui = { version = "9.0.2", features = ["axum"] }
utoipa-axum = "0.2.0"
utoipauto = "0.2.0"
seaography = { version = "2.0.0-rc.9", features = [
  "with-decimal",
  "with-chrono",
  "with-postgres-array",
  "with-uuid",
] }
async-graphql-axum = "7.0.17"
async-graphql = "7.0.17"
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
base64 = "0.22.1"
bcrypt = "0.19.2"
validator = { version = "0.20.0", features = ["derive"] }
clap = { version = "4.6.4", features = ["derive"] }
serde_yaml_ng = "0.10.0"
sha2 = "0.11.0"
rand = "0.10.2"
async-trait = "0.1.91"

[dev-dependencies]
mockall = "0.15.0"
tokio-test = "0.4.5"
tower = { version = "0.5.3", features = ["util"] }
http-body-util = "0.1.4"
assert-json-diff = "2.0.2"
